#!/usr/bin/python

# An ECB/CBC detection oracle
# Now that you have ECB and CBC working:
# 
# Write a function to generate a random AES key; that's just 16 random bytes.
# 
# Write a function that encrypts data under an unknown key --- that is, a function that generates a random key and encrypts under it.
# 
# The function should look like:
# 
# encryption_oracle(your-input)
# => [MEANINGLESS JIBBER JABBER]
# Under the hood, have the function append 5-10 bytes (count chosen randomly) before the plaintext and 5-10 bytes after the plaintext.
# 
# Now, have the function choose to encrypt under ECB 1/2 the time, and under CBC the other half (just use random IVs each time for CBC). Use rand(2) to decide which to use.
# 
# Detect the block cipher mode the function is using each time. You should end up with a piece of code that, pointed at a block box that might be encrypting ECB or CBC, tells you which one is happening.

hexString2string = lambda s: s.decode("hex")
string2hexString = lambda s: s.encode("hex")
stringStringXor = lambda s1, s2: ''.join(chr(ord(a) ^ ord(b)) for a,b in zip(s1, s2))

from Crypto.Cipher import AES
pad = lambda s, l: s + (l - len(s) % l) * chr(l - len(s) % l)
unpad = lambda s: s[:-ord(s[-1:])]
encodeECB = lambda key, s: AES.new(key).encrypt(pad(s, len(key)))
decodeECB = lambda key, s: unpad(AES.new(key).decrypt(s))

BLOCKSIZE = 16
def decodeCBC(key, IV, cipherText):
	plainText = ''
	offset = 0
	aes = AES.new(key)
	while offset < len(cipherText):
		cipherBlock = cipherText[offset:offset+BLOCKSIZE]
		ecbBlock = aes.decrypt(cipherBlock)
		plainBlock = stringStringXor(ecbBlock, IV)
		plainText += plainBlock
		IV = cipherBlock
		offset += BLOCKSIZE

	# strip off padding bytes
	plainText = plainText[:-ord(plainText[-1:])]
	return plainText

def encodeCBC(key, IV, plainText):
	cipherText = ''
	offset = 0
	aes = AES.new(key)
	while offset < len(plainText):
		plainBlock = plainText[offset:offset+BLOCKSIZE]
		# add padding
		if len(plainBlock) < BLOCKSIZE:
			c = BLOCKSIZE - len(plainBlock)
			plainBlock += chr(c) * c
		ecbBlock = stringStringXor(plainBlock, IV)
		cipherBlock = aes.encrypt(ecbBlock)
		cipherText += cipherBlock
		IV = cipherBlock
		offset += BLOCKSIZE

	# add padding if last byte exactly on BLOCKSIZE boundary
	if offset == len(plainText):
		c = BLOCKSIZE
		plainBlock = chr(c) * c
		ecbBlock = stringStringXor(plainBlock, IV)
		cipherBlock = aes.encrypt(ecbBlock)
		cipherText += cipherBlock

	return cipherText

from random import randint
def randomString(n):
	result =""
	for x in range(0, n):
		result += chr(randint(0, 255))
	return result
	
def encryptionOracle(data):
	data = randomString(randint(5, 10)) + data + randomString(randint(5, 10))
	key = randomString(BLOCKSIZE)
	encryptMode = randint(0, 1)
	print "encrypted with",
	if encryptMode == 0:
		print "ECB -->",
		return encodeECB(key, data)
	else:
		print "CBC -->",
		IV = randomString(BLOCKSIZE)
		return encodeCBC(key, IV, data)

def detectEncryption(encryptedData):
	# first block (1) & last block (4) contains 5-10 random unknown bytes added in encryptionOracle
	# so we can only use intermediate blocks 2 & 3 to check for equal content
	if encryptedData[BLOCKSIZE * 1:BLOCKSIZE * 2] == encryptedData[BLOCKSIZE * 2:BLOCKSIZE * 3]:
		print "ECB"
	else:
		print "CBC"

# must be larger than 3 * BLOCKSIZE - minimum number of added random unknown bytes = 48 - 5 = 43
# if less, detectEncryption is not able to do a proper comparison of two blocks 
plainText = " " * 43

for i in range(1, 20):
	encryptedData = encryptionOracle(plainText)
	detectEncryption(encryptedData)
	



